# Generated by Django 3.0.7 on 2020-08-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpticket',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='helpticket',
            name='contact',
            field=models.CharField(max_length=150),
        ),
    ]
