# Generated by Django 3.0.7 on 2020-08-10 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='helpticket',
            options={'ordering': ['-updated_at']},
        ),
    ]
