# Generated by Django 3.0.7 on 2020-08-06 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helpticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpticket',
            name='category',
            field=models.CharField(choices=[(1, 'Urgent'), (2, 'Normal')], default='2', max_length=300),
        ),
        migrations.AddField(
            model_name='helpticket',
            name='city',
            field=models.CharField(default='Istanbul', max_length=100),
        ),
        migrations.AddField(
            model_name='helpticket',
            name='owner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
