# Generated by Django 3.0.7 on 2020-08-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpticket', '0002_auto_20200806_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpticket',
            name='category',
            field=models.CharField(choices=[('urgent', 'Urgent'), ('normal', 'Normal')], default='urgent', max_length=300),
        ),
    ]
