# Generated by Django 3.0.7 on 2020-08-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpticket', '0002_auto_20200814_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpticket',
            name='categories',
            field=models.ManyToManyField(related_name='ticket_category', to='helpticket.HelpCategory', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='helpticket',
            name='city',
            field=models.CharField(max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='helpticket',
            name='contact',
            field=models.CharField(max_length=150, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='helpticket',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
    ]
