# Generated by Django 3.0.7 on 2020-08-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpticket', '0003_auto_20200806_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpticket',
            name='contact',
            field=models.CharField(default='dodo', max_length=150),
            preserve_default=False,
        ),
    ]
