# Generated by Django 3.0.7 on 2020-08-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpticket', '0004_helpticket_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpticket',
            name='contact',
            field=models.CharField(default='İletişim Bilgileri', max_length=150),
        ),
    ]
